"""fixed sendor messages

Revision ID: 1a15d8d7b749
Revises: eac9a50e5543
Create Date: 2024-11-02 08:55:06.151109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a15d8d7b749'
down_revision: Union[str, None] = 'eac9a50e5543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
