"""Added device detal model

Revision ID: 29ecf8b2ba75
Revises: 1a15d8d7b749
Create Date: 2024-11-04 14:23:55.563033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29ecf8b2ba75'
down_revision: Union[str, None] = '1a15d8d7b749'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('device_name', sa.String(length=255), nullable=False))
    op.add_column('device', sa.Column('device_model', sa.String(length=255), nullable=True))
    op.add_column('device', sa.Column('location', sa.String(length=255), nullable=True))
    op.drop_column('device', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('name', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('device', 'location')
    op.drop_column('device', 'device_model')
    op.drop_column('device', 'device_name')
    # ### end Alembic commands ###
