"""Added registered_at and updated_at field

Revision ID: a0b464e2e21d
Revises: 29ecf8b2ba75
Create Date: 2024-11-04 14:29:44.703858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b464e2e21d'
down_revision: Union[str, None] = '29ecf8b2ba75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('registered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('device', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'updated_at')
    op.drop_column('device', 'registered_at')
    # ### end Alembic commands ###
